site_name: Badgepack
repo_url: https://github.com/lestrato/badgepack
pages:
    - Home: index.md
    - Guides:
        - Installation and Setup: guides/setup.md
        - Editing the Docs: guides/editing-docs.md
        - FAQ: guides/faq.md
    - Project Documentation:
        - Apps:
            - Account: project/apps/account.md
            - Badge: project/apps/badge.md
            - Base: project/apps/base.md
            - Community: project/apps/community.md
        - Media Files: project/media.md
        - Static Files: project/static.md
        - URLs: project/urls.md
    - Project Status:
        - Bugs: status/bugs.md
        - Future Work: status/sprints.md
    - Human Resources:
        - Usability Testing: human_resources/test-script.md
        - Meet the Team: human_resources/contact.md

theme: readthedocs
