site_name: Badgepack
repo_url: https://github.com/lestrato/badgepack
pages:
    - Home: index.md
    - Usability Testing: test-script.md
    - Guides:
        - Installation and Setup: guides/setup.md
        - Editing the Docs: guides/editing-docs.md
        - FAQ: faq.md
    - Project Documentation:
        - URLs: project/urls.md
        - Static Files and CSS: project/static.md
        - Account: project/account.md
        - Badge: project/badge.md
        - Base: project/base.md
        - Community: project/community.md
    - Project Status:
        - To-do Lists: status/todo.md
        - Backlog: status/backlog.md
        - Sprints and Future Work: status/sprints.md
        - Bugs: status/bugs.md

theme: readthedocs
