# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20161018_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='tag',
            field=models.CharField(max_length=10),
        ),
    ]
