# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0003_auto_20161018_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('accepted_on', models.DateField(default=datetime.datetime.now)),
                ('accepted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_accepted_by', to=settings.AUTH_USER_MODEL)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applciation_applicant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'application',
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('accepted_on', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'invitation',
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
            },
        ),
        migrations.AlterField(
            model_name='community',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_recipient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invitation',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitation_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='application',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
