# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 18:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_auto_20161021_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='applications',
            field=models.ManyToManyField(related_name='community_applications', through='community.Application', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='community',
            name='invitations',
            field=models.ManyToManyField(related_name='community_invitations', through='community.Invitation', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='community',
            name='members',
            field=models.ManyToManyField(related_name='community_members', through='community.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
