# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 22:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_auto_20161022_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='to_be_moderator',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_applicant', to=settings.AUTH_USER_MODEL),
        ),
    ]
