# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 04:24
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import randomslugfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=140)),
                ('image', models.ImageField(upload_to='uploads/badges/')),
                ('slug', randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, unique=True)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('is_available', models.BooleanField(default=False)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('earnable_by', models.CharField(choices=[('e', 'earner'), ('m', 'moderator')], default='e', max_length=1)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeclass_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'badgeclass',
                'verbose_name': 'class',
                'verbose_name_plural': 'classes',
            },
        ),
        migrations.CreateModel(
            name='BadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_on', models.DateField(default=datetime.datetime.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badgeinstance_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.BadgeClass')),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeinstance_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'badgeinstance',
                'verbose_name': 'instance',
                'verbose_name_plural': 'instances',
            },
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='instances',
            field=models.ManyToManyField(related_name='badgeclass_instances', through='badge.BadgeInstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
