# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 01:39
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('description', models.CharField(max_length=140)),
                ('image', models.ImageField(height_field=150, upload_to='uploads/%Y/%m/%d/', width_field=150)),
                ('created_on', models.DateField(default=datetime.datetime.now)),
                ('is_available', models.BooleanField(default=False)),
                ('is_discontinued', models.BooleanField(default=False)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeclass_creator', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'badgeclass',
                'verbose_name': 'badgeclass',
                'verbose_name_plural': 'badgeclasses',
            },
        ),
        migrations.CreateModel(
            name='BadgeInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recieved_on', models.DateField(default=datetime.datetime.now)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badgeinstance_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('badge_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='badge.BadgeClass')),
                ('earner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badgeinstance_recipient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'badgeinstance',
                'verbose_name': 'badgeinstance',
                'verbose_name_plural': 'badgeinstances',
            },
        ),
        migrations.AddField(
            model_name='badgeclass',
            name='instances',
            field=models.ManyToManyField(related_name='badgeclass_instances', through='badge.BadgeInstance', to=settings.AUTH_USER_MODEL),
        ),
    ]
