# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='earnable_by',
            field=models.CharField(choices=[('earner', 'earner'), ('moderator', 'moderator')], default='earner', max_length=10),
        ),
    ]
