# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 06:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0002_auto_20161029_2146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgeclass',
            options={'verbose_name': 'class', 'verbose_name_plural': 'classes'},
        ),
        migrations.AlterModelOptions(
            name='badgeinstance',
            options={'verbose_name': 'instance', 'verbose_name_plural': 'instances'},
        ),
        migrations.AlterField(
            model_name='badgeclass',
            name='image',
            field=models.ImageField(upload_to='uploads/badges/'),
        ),
    ]
