# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0003_auto_20161030_0239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badgeclass',
            name='image',
            field=models.ImageField(default='images/uploadimage.png', upload_to='uploads/badges/'),
        ),
    ]
