# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-13 01:17
from __future__ import unicode_literals

from django.db import migrations, models
import randomslugfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('badge', '0009_auto_20161112_1649'),
    ]

    operations = [
        migrations.AddField(
            model_name='badgeclass',
            name='slug',
            field=randomslugfield.fields.RandomSlugField(blank=True, editable=False, length=7, max_length=7, unique=True),
        ),
        migrations.AlterField(
            model_name='badgeclass',
            name='image',
            field=models.ImageField(upload_to='uploads/badges/'),
        ),
    ]
