# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 01:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='is_moderator',
        ),
        migrations.AddField(
            model_name='membership',
            name='user_status',
            field=models.CharField(choices=[('earner', 'earner'), ('moderator', 'moderator'), ('owner', 'owner')], default='earner', max_length=10),
        ),
    ]
