# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-22 05:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_auto_20161122_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='user_status',
            field=models.CharField(choices=[('earner', 'earner'), ('moderator', 'moderator'), ('owner', 'owner')], default='earner', max_length=10),
        ),
    ]
